# Generated by Django 2.2.6 on 2019-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='wesite',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
