# Generated by Django 2.2.6 on 2019-10-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191009_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wesite',
            new_name='website',
        ),
    ]
