# Generated by Django 2.2.6 on 2019-10-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191009_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
